// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwbjdkxjpghiqayzppxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3Ympka3hqcGdoaXFheXpwcHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MzI0MTksImV4cCI6MjA1OTMwODQxOX0.8dGVRpIJfHMTOq0-WHnRfDakDgxOJH7I85vpBoCxe1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);